### ISSUE TITLE
Discuss: Should `metadata.json` link be mandatory ?

### ISSUE THREAD

**Issue by Gozala** [nftstorage/ipnft#1]
Moving discussion from hackmd to here, per @alanshaw in regards to

https://github.com/nftstorage/ipnft/blob/1ae1dcb55ac3e8e2f5817363da4d5b87ff16dc1c/Readme.md?plain=1#L56

> It is mandatory no? This is the document that MUST be linked to from tokenURI

**Comment by Gozala** [comment]
I think it’s up to us to decide. Originally we included `metadata.json` as to not force anything on nft.storage users, especially because gateway responds with error on IPNFT cids. 

I think we don’t have to demand this, but maybe there is a good reason that I’m overlooking ?

**Comment by alanshaw** [comment]
Looking at the ERC721 spec it does say _MAY_ so I think you're right, it should be optional.

**Comment by Gozala** [comment]
> Looking at the ERC721 spec it does say _MAY_ so I think you're right, it should be optional.

I'm assuming your referring to this section:

> The URI may point to a JSON file that conforms to the "ERC721 Metadata JSON Schema"

If so I do not think it is relevant here, because IPNFT is for the NFTs that do have metadata. That said I felt like putting `metadata.json` was a stop gap solution, not to force IPLD stack on anyone. My hope was that in long term it would become obsolete.

That is a rational for leaving it out. That said maybe there is a compelling reason to make it mandatory.

@mikeal do you have opinions ?
